/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as KbRouteImport } from './routes/kb'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmailPendingRouteImport } from './routes/_authenticated/email-pending'
import { Route as AuthenticatedEquipmentsRouteImport } from './routes/_authenticated/equipments'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedWhatsappPendingRouteImport } from './routes/_authenticated/whatsapp-pending'
import { Route as BackendSplatRouteImport } from './routes/backend/$'
import { Route as CsatTokenRouteImport } from './routes/csat.$token'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoClientesRouteImport } from './routes/demo.Clientes'
import { Route as DemoContratosRouteImport } from './routes/demo.Contratos'
import { Route as DemoDashboardRouteImport } from './routes/demo.Dashboard'
import { Route as DemoTicketsRouteImport } from './routes/demo.Tickets'
import { Route as KbIndexRouteImport } from './routes/kb.index'
import { Route as KbSlugRouteImport } from './routes/kb.$slug'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as AuthenticatedKbAdminRouteImport } from './routes/_authenticated/kb.admin'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as DemoTicketsIdRouteImport } from './routes/demo.Tickets.$id'
import { Route as ApiPublicPortalChatStartRouteImport } from './routes/api/public/portal/chat-start'
import { Route as ApiPublicPortalRequestOtpRouteImport } from './routes/api/public/portal/request-otp'
import { Route as ApiPublicPortalSessionRouteImport } from './routes/api/public/portal/session'
import { Route as ApiPublicPortalTicketDetailRouteImport } from './routes/api/public/portal/ticket-detail'
import { Route as ApiPublicPortalTicketReplyRouteImport } from './routes/api/public/portal/ticket-reply'
import { Route as ApiPublicPortalTicketsRouteImport } from './routes/api/public/portal/tickets'
import { Route as ApiPublicPortalVerifyOtpRouteImport } from './routes/api/public/portal/verify-otp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRoute = KbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailPendingRoute =
  AuthenticatedEmailPendingRouteImport.update({
    id: '/email-pending',
    path: '/email-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentsRoute = AuthenticatedEquipmentsRouteImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappPendingRoute =
  AuthenticatedWhatsappPendingRouteImport.update({
    id: '/whatsapp-pending',
    path: '/whatsapp-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BackendSplatRoute = BackendSplatRouteImport.update({
  id: '/backend/$',
  path: '/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CsatTokenRoute = CsatTokenRouteImport.update({
  id: '/csat/$token',
  path: '/csat/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientesRoute = DemoClientesRouteImport.update({
  id: '/Clientes',
  path: '/Clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoContratosRoute = DemoContratosRouteImport.update({
  id: '/Contratos',
  path: '/Contratos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoTicketsRoute = DemoTicketsRouteImport.update({
  id: '/Tickets',
  path: '/Tickets',
  getParentRoute: () => DemoRoute,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KbRoute,
} as any)
const KbSlugRoute = KbSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KbRoute,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKbAdminRoute = AuthenticatedKbAdminRouteImport.update({
  id: '/kb/admin',
  path: '/kb/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const DemoTicketsIdRoute = DemoTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DemoTicketsRoute,
} as any)
const ApiPublicPortalChatStartRoute =
  ApiPublicPortalChatStartRouteImport.update({
    id: '/api/public/portal/chat-start',
    path: '/api/public/portal/chat-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalRequestOtpRoute =
  ApiPublicPortalRequestOtpRouteImport.update({
    id: '/api/public/portal/request-otp',
    path: '/api/public/portal/request-otp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalSessionRoute = ApiPublicPortalSessionRouteImport.update({
  id: '/api/public/portal/session',
  path: '/api/public/portal/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalTicketDetailRoute =
  ApiPublicPortalTicketDetailRouteImport.update({
    id: '/api/public/portal/ticket-detail',
    path: '/api/public/portal/ticket-detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalTicketReplyRoute =
  ApiPublicPortalTicketReplyRouteImport.update({
    id: '/api/public/portal/ticket-reply',
    path: '/api/public/portal/ticket-reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalTicketsRoute = ApiPublicPortalTicketsRouteImport.update({
  id: '/api/public/portal/tickets',
  path: '/api/public/portal/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalVerifyOtpRoute =
  ApiPublicPortalVerifyOtpRouteImport.update({
    id: '/api/public/portal/verify-otp',
    path: '/api/public/portal/verify-otp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/kb': typeof KbRouteWithChildren
  '/portal': typeof PortalRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-pending': typeof AuthenticatedEmailPendingRoute
  '/equipments': typeof AuthenticatedEquipmentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/whatsapp-pending': typeof AuthenticatedWhatsappPendingRoute
  '/backend/$': typeof BackendSplatRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/Clientes': typeof DemoClientesRoute
  '/demo/Contratos': typeof DemoContratosRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Tickets': typeof DemoTicketsRouteWithChildren
  '/kb/$slug': typeof KbSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/kb/': typeof KbIndexRoute
  '/kb/admin': typeof AuthenticatedKbAdminRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/demo/Tickets/$id': typeof DemoTicketsIdRoute
  '/api/public/portal/chat-start': typeof ApiPublicPortalChatStartRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/session': typeof ApiPublicPortalSessionRoute
  '/api/public/portal/ticket-detail': typeof ApiPublicPortalTicketDetailRoute
  '/api/public/portal/ticket-reply': typeof ApiPublicPortalTicketReplyRoute
  '/api/public/portal/tickets': typeof ApiPublicPortalTicketsRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-pending': typeof AuthenticatedEmailPendingRoute
  '/equipments': typeof AuthenticatedEquipmentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/whatsapp-pending': typeof AuthenticatedWhatsappPendingRoute
  '/backend/$': typeof BackendSplatRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/Clientes': typeof DemoClientesRoute
  '/demo/Contratos': typeof DemoContratosRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Tickets': typeof DemoTicketsRouteWithChildren
  '/kb/$slug': typeof KbSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/demo': typeof DemoIndexRoute
  '/kb': typeof KbIndexRoute
  '/kb/admin': typeof AuthenticatedKbAdminRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/demo/Tickets/$id': typeof DemoTicketsIdRoute
  '/api/public/portal/chat-start': typeof ApiPublicPortalChatStartRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/session': typeof ApiPublicPortalSessionRoute
  '/api/public/portal/ticket-detail': typeof ApiPublicPortalTicketDetailRoute
  '/api/public/portal/ticket-reply': typeof ApiPublicPortalTicketReplyRoute
  '/api/public/portal/tickets': typeof ApiPublicPortalTicketsRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/kb': typeof KbRouteWithChildren
  '/portal': typeof PortalRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-pending': typeof AuthenticatedEmailPendingRoute
  '/_authenticated/equipments': typeof AuthenticatedEquipmentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/_authenticated/whatsapp-pending': typeof AuthenticatedWhatsappPendingRoute
  '/backend/$': typeof BackendSplatRoute
  '/csat/$token': typeof CsatTokenRoute
  '/demo/Clientes': typeof DemoClientesRoute
  '/demo/Contratos': typeof DemoContratosRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Tickets': typeof DemoTicketsRouteWithChildren
  '/kb/$slug': typeof KbSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/kb/': typeof KbIndexRoute
  '/_authenticated/kb/admin': typeof AuthenticatedKbAdminRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/demo/Tickets/$id': typeof DemoTicketsIdRoute
  '/api/public/portal/chat-start': typeof ApiPublicPortalChatStartRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/session': typeof ApiPublicPortalSessionRoute
  '/api/public/portal/ticket-detail': typeof ApiPublicPortalTicketDetailRoute
  '/api/public/portal/ticket-reply': typeof ApiPublicPortalTicketReplyRoute
  '/api/public/portal/tickets': typeof ApiPublicPortalTicketsRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/kb'
    | '/portal'
    | '/contacts'
    | '/contracts'
    | '/customers'
    | '/dashboard'
    | '/email-pending'
    | '/equipments'
    | '/finance'
    | '/reports'
    | '/settings'
    | '/tickets'
    | '/whatsapp-pending'
    | '/backend/$'
    | '/csat/$token'
    | '/demo/Clientes'
    | '/demo/Contratos'
    | '/demo/Dashboard'
    | '/demo/Tickets'
    | '/kb/$slug'
    | '/report/$token'
    | '/demo/'
    | '/kb/'
    | '/kb/admin'
    | '/tickets/$id'
    | '/demo/Tickets/$id'
    | '/api/public/portal/chat-start'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/session'
    | '/api/public/portal/ticket-detail'
    | '/api/public/portal/ticket-reply'
    | '/api/public/portal/tickets'
    | '/api/public/portal/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/contacts'
    | '/contracts'
    | '/customers'
    | '/dashboard'
    | '/email-pending'
    | '/equipments'
    | '/finance'
    | '/reports'
    | '/settings'
    | '/tickets'
    | '/whatsapp-pending'
    | '/backend/$'
    | '/csat/$token'
    | '/demo/Clientes'
    | '/demo/Contratos'
    | '/demo/Dashboard'
    | '/demo/Tickets'
    | '/kb/$slug'
    | '/report/$token'
    | '/demo'
    | '/kb'
    | '/kb/admin'
    | '/tickets/$id'
    | '/demo/Tickets/$id'
    | '/api/public/portal/chat-start'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/session'
    | '/api/public/portal/ticket-detail'
    | '/api/public/portal/ticket-reply'
    | '/api/public/portal/tickets'
    | '/api/public/portal/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/kb'
    | '/portal'
    | '/_authenticated/contacts'
    | '/_authenticated/contracts'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-pending'
    | '/_authenticated/equipments'
    | '/_authenticated/finance'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tickets'
    | '/_authenticated/whatsapp-pending'
    | '/backend/$'
    | '/csat/$token'
    | '/demo/Clientes'
    | '/demo/Contratos'
    | '/demo/Dashboard'
    | '/demo/Tickets'
    | '/kb/$slug'
    | '/report/$token'
    | '/demo/'
    | '/kb/'
    | '/_authenticated/kb/admin'
    | '/_authenticated/tickets/$id'
    | '/demo/Tickets/$id'
    | '/api/public/portal/chat-start'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/session'
    | '/api/public/portal/ticket-detail'
    | '/api/public/portal/ticket-reply'
    | '/api/public/portal/tickets'
    | '/api/public/portal/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRouteWithChildren
  KbRoute: typeof KbRouteWithChildren
  PortalRoute: typeof PortalRoute
  BackendSplatRoute: typeof BackendSplatRoute
  CsatTokenRoute: typeof CsatTokenRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ApiPublicPortalChatStartRoute: typeof ApiPublicPortalChatStartRoute
  ApiPublicPortalRequestOtpRoute: typeof ApiPublicPortalRequestOtpRoute
  ApiPublicPortalSessionRoute: typeof ApiPublicPortalSessionRoute
  ApiPublicPortalTicketDetailRoute: typeof ApiPublicPortalTicketDetailRoute
  ApiPublicPortalTicketReplyRoute: typeof ApiPublicPortalTicketReplyRoute
  ApiPublicPortalTicketsRoute: typeof ApiPublicPortalTicketsRoute
  ApiPublicPortalVerifyOtpRoute: typeof ApiPublicPortalVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-pending': {
      id: '/_authenticated/email-pending'
      path: '/email-pending'
      fullPath: '/email-pending'
      preLoaderRoute: typeof AuthenticatedEmailPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipments': {
      id: '/_authenticated/equipments'
      path: '/equipments'
      fullPath: '/equipments'
      preLoaderRoute: typeof AuthenticatedEquipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-pending': {
      id: '/_authenticated/whatsapp-pending'
      path: '/whatsapp-pending'
      fullPath: '/whatsapp-pending'
      preLoaderRoute: typeof AuthenticatedWhatsappPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/backend/$': {
      id: '/backend/$'
      path: '/backend/$'
      fullPath: '/backend/$'
      preLoaderRoute: typeof BackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csat/$token': {
      id: '/csat/$token'
      path: '/csat/$token'
      fullPath: '/csat/$token'
      preLoaderRoute: typeof CsatTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Clientes': {
      id: '/demo/Clientes'
      path: '/Clientes'
      fullPath: '/demo/Clientes'
      preLoaderRoute: typeof DemoClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Contratos': {
      id: '/demo/Contratos'
      path: '/Contratos'
      fullPath: '/demo/Contratos'
      preLoaderRoute: typeof DemoContratosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Dashboard': {
      id: '/demo/Dashboard'
      path: '/Dashboard'
      fullPath: '/demo/Dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Tickets': {
      id: '/demo/Tickets'
      path: '/Tickets'
      fullPath: '/demo/Tickets'
      preLoaderRoute: typeof DemoTicketsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/kb/': {
      id: '/kb/'
      path: '/'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof KbRoute
    }
    '/kb/$slug': {
      id: '/kb/$slug'
      path: '/$slug'
      fullPath: '/kb/$slug'
      preLoaderRoute: typeof KbSlugRouteImport
      parentRoute: typeof KbRoute
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kb/admin': {
      id: '/_authenticated/kb/admin'
      path: '/kb/admin'
      fullPath: '/kb/admin'
      preLoaderRoute: typeof AuthenticatedKbAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/demo/Tickets/$id': {
      id: '/demo/Tickets/$id'
      path: '/$id'
      fullPath: '/demo/Tickets/$id'
      preLoaderRoute: typeof DemoTicketsIdRouteImport
      parentRoute: typeof DemoTicketsRoute
    }
    '/api/public/portal/chat-start': {
      id: '/api/public/portal/chat-start'
      path: '/api/public/portal/chat-start'
      fullPath: '/api/public/portal/chat-start'
      preLoaderRoute: typeof ApiPublicPortalChatStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/request-otp': {
      id: '/api/public/portal/request-otp'
      path: '/api/public/portal/request-otp'
      fullPath: '/api/public/portal/request-otp'
      preLoaderRoute: typeof ApiPublicPortalRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/session': {
      id: '/api/public/portal/session'
      path: '/api/public/portal/session'
      fullPath: '/api/public/portal/session'
      preLoaderRoute: typeof ApiPublicPortalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/ticket-detail': {
      id: '/api/public/portal/ticket-detail'
      path: '/api/public/portal/ticket-detail'
      fullPath: '/api/public/portal/ticket-detail'
      preLoaderRoute: typeof ApiPublicPortalTicketDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/ticket-reply': {
      id: '/api/public/portal/ticket-reply'
      path: '/api/public/portal/ticket-reply'
      fullPath: '/api/public/portal/ticket-reply'
      preLoaderRoute: typeof ApiPublicPortalTicketReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/tickets': {
      id: '/api/public/portal/tickets'
      path: '/api/public/portal/tickets'
      fullPath: '/api/public/portal/tickets'
      preLoaderRoute: typeof ApiPublicPortalTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/verify-otp': {
      id: '/api/public/portal/verify-otp'
      path: '/api/public/portal/verify-otp'
      fullPath: '/api/public/portal/verify-otp'
      preLoaderRoute: typeof ApiPublicPortalVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailPendingRoute: typeof AuthenticatedEmailPendingRoute
  AuthenticatedEquipmentsRoute: typeof AuthenticatedEquipmentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
  AuthenticatedWhatsappPendingRoute: typeof AuthenticatedWhatsappPendingRoute
  AuthenticatedKbAdminRoute: typeof AuthenticatedKbAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailPendingRoute: AuthenticatedEmailPendingRoute,
  AuthenticatedEquipmentsRoute: AuthenticatedEquipmentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
  AuthenticatedWhatsappPendingRoute: AuthenticatedWhatsappPendingRoute,
  AuthenticatedKbAdminRoute: AuthenticatedKbAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoTicketsRouteChildren {
  DemoTicketsIdRoute: typeof DemoTicketsIdRoute
}

const DemoTicketsRouteChildren: DemoTicketsRouteChildren = {
  DemoTicketsIdRoute: DemoTicketsIdRoute,
}

const DemoTicketsRouteWithChildren = DemoTicketsRoute._addFileChildren(
  DemoTicketsRouteChildren,
)

interface DemoRouteChildren {
  DemoClientesRoute: typeof DemoClientesRoute
  DemoContratosRoute: typeof DemoContratosRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoTicketsRoute: typeof DemoTicketsRouteWithChildren
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoClientesRoute: DemoClientesRoute,
  DemoContratosRoute: DemoContratosRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoTicketsRoute: DemoTicketsRouteWithChildren,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface KbRouteChildren {
  KbSlugRoute: typeof KbSlugRoute
  KbIndexRoute: typeof KbIndexRoute
}

const KbRouteChildren: KbRouteChildren = {
  KbSlugRoute: KbSlugRoute,
  KbIndexRoute: KbIndexRoute,
}

const KbRouteWithChildren = KbRoute._addFileChildren(KbRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRouteWithChildren,
  KbRoute: KbRouteWithChildren,
  PortalRoute: PortalRoute,
  BackendSplatRoute: BackendSplatRoute,
  CsatTokenRoute: CsatTokenRoute,
  ReportTokenRoute: ReportTokenRoute,
  ApiPublicPortalChatStartRoute: ApiPublicPortalChatStartRoute,
  ApiPublicPortalRequestOtpRoute: ApiPublicPortalRequestOtpRoute,
  ApiPublicPortalSessionRoute: ApiPublicPortalSessionRoute,
  ApiPublicPortalTicketDetailRoute: ApiPublicPortalTicketDetailRoute,
  ApiPublicPortalTicketReplyRoute: ApiPublicPortalTicketReplyRoute,
  ApiPublicPortalTicketsRoute: ApiPublicPortalTicketsRoute,
  ApiPublicPortalVerifyOtpRoute: ApiPublicPortalVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
